import { useState } from 'react';
import { Play, CheckCircle, Loader2, Swords, Trophy, Clock, Code, MessageSquare, FileCode2 } from 'lucide-react';
import { MODEL_REGISTRY, queryAllModels, evaluateCodeSubmission } from '../services/aiService';
import { extractCode } from '../utils/codeExtractor';
import { supabase } from '../services/supabaseClient';

const ArenaResultCard = ({ result, isWinner }) => {
  const [activeTab, setActiveTab] = useState('feedback');

  return (
    <div className="relative bg-white/[0.02] border border-white/10 rounded-2xl p-6 overflow-hidden">
      
      {/* Winner Banner */}
      {isWinner && (
        <div className="absolute top-0 right-0 bg-yellow-500/10 text-yellow-500 text-[10px] font-bold uppercase tracking-wider px-3 py-1 rounded-bl-lg border-b border-l border-yellow-500/20 flex items-center gap-1.5">
          <Trophy className="w-3 h-3" /> Winner
        </div>
      )}

      <div className="flex flex-col md:flex-row md:items-start gap-6">
        
        {/* Score Ring */}
        <div className="flex-shrink-0 flex flex-col items-center justify-center w-24 h-24 rounded-full border-4 border-white/5 bg-zinc-950 relative">
          <span className={`text-2xl font-bold ${result.success ? 'text-emerald-400' : 'text-red-400'}`}>
            {result.score}
          </span>
          <span className="text-[10px] text-zinc-500 uppercase font-semibold">Score</span>
        </div>

        {/* Data Payload */}
        <div className="flex-1 space-y-4">
          <div className="flex items-center gap-3">
            <h3 className="text-lg font-bold text-white">{result.model}</h3>
            <span className="text-xs px-2 py-0.5 rounded bg-white/5 text-zinc-400 border border-white/10">{result.provider}</span>
          </div>
          
          {/* Tab Controls */}
          <div className="flex items-center gap-2 border-b border-white/5 pb-2">
            <button
              onClick={() => setActiveTab('feedback')}
              className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-md transition-all ${
                activeTab === 'feedback' ? 'bg-indigo-500/10 text-indigo-400' : 'text-zinc-500 hover:text-zinc-300'
              }`}
            >
              <MessageSquare className="w-3.5 h-3.5" /> Judge Feedback
            </button>
            <button
              onClick={() => setActiveTab('code')}
              className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-md transition-all ${
                activeTab === 'code' ? 'bg-indigo-500/10 text-emerald-400' : 'text-zinc-500 hover:text-zinc-300'
              }`}
            >
              <FileCode2 className="w-3.5 h-3.5" /> Generated Code
            </button>
          </div>

          {/* Tab Content View */}
          {activeTab === 'feedback' ? (
            <div className="p-4 rounded-lg bg-zinc-950 border border-white/5 text-sm text-zinc-300 leading-relaxed min-h-[100px]">
              {result.feedback}
            </div>
          ) : (
            <div className="p-4 rounded-lg bg-[#0c0c0e] border border-white/5 text-xs text-emerald-400 font-mono whitespace-pre-wrap overflow-x-auto max-h-[300px]">
              {result.code || "// No code was generated by this model."}
            </div>
          )}

          {/* Metrics Footer */}
          <div className="flex items-center gap-4 text-xs font-medium text-zinc-500 pt-2">
            <div className="flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5" />
              {result.responseTimeMs}ms
            </div>
            <div className="flex items-center gap-1.5">
              <Code className="w-3.5 h-3.5" />
              {result.outputTokens} tokens
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default function Arena() {
  const [prompt, setPrompt] = useState('');
  const [selectedModels, setSelectedModels] = useState([]);
  const [isRunning, setIsRunning] = useState(false);
  const [results, setResults] = useState([]);

  // Toggle model selection
  const handleToggleModel = (modelId) => {
    setSelectedModels(prev => 
      prev.includes(modelId) 
        ? prev.filter(id => id !== modelId)
        : [...prev, modelId]
    );
  };

  const handleRunArena = async () => {
    if (!prompt.trim()) return alert("Please enter a challenge prompt.");
    if (selectedModels.length < 2) return alert("Please select at least 2 models for the arena.");

    setIsRunning(true);
    setResults([]);

    try {
      // PHASE 1: Parallel Generation
      const generations = await queryAllModels(prompt, selectedModels);

      // PHASE 2: Parallel Evaluation & Database Push (Fortified)
      const gradedResults = await Promise.all(generations.map(async (gen) => {
        const safeTime = gen.responseTimeMs || 0;
        const safeTokens = gen.outputTokens || 0;

        if (!gen.success) {
          return { ...gen, score: 0, feedback: gen.error || "Unknown Error", code: 'Generation failed.', responseTimeMs: safeTime, outputTokens: safeTokens };
        }

        const pureCode = extractCode(gen.content) || gen.content;
        
        try {
          const evalResult = await evaluateCodeSubmission(prompt, pureCode, 'qwen-3-32b');
          
          const cleanScore = Number(evalResult?.score) || 0;
          let cleanFeedback = "No feedback provided.";
          if (evalResult?.feedback) {
            cleanFeedback = typeof evalResult.feedback === 'object' 
              ? JSON.stringify(evalResult.feedback, null, 2) 
              : String(evalResult.feedback);
          }

          // Lock results into Supabase
          const { error: dbError } = await supabase
            .from('evaluations')
            .insert([
              {
                model_id: gen.modelId,
                challenge_prompt: prompt,
                correctness: evalResult.metrics?.correctness || 0,
                efficiency: evalResult.metrics?.efficiency || 0,
                readability: evalResult.metrics?.readability || 0,
                explanation: evalResult.metrics?.explanation || 0,
                security: evalResult.metrics?.security || 0,
                weighted_total: cleanScore,
                notes: cleanFeedback,
                test_results: evalResult.simulatedExecution || {},
                is_auto_scored: true
              }
            ]);

          if (dbError) {
            console.error(`Supabase save failed for ${gen.modelId}:`, dbError.message);
          } else {
            console.log(`✅ Saved ${gen.modelId} evaluation to cloud!`);
          }

          // Return mapped object to UI
          return { 
            ...gen, 
            code: pureCode, 
            score: cleanScore, 
            feedback: cleanFeedback,
            metrics: evalResult.metrics,
            responseTimeMs: safeTime,
            outputTokens: safeTokens
          };

        } catch (e) {
          console.error(`Evaluation failed for ${gen.modelId}:`, e);
          return { 
            ...gen, 
            code: pureCode, 
            score: 0, 
            feedback: `Evaluation Engine Error: ${e.message}`,
            responseTimeMs: safeTime,
            outputTokens: safeTokens
          };
        }
      }));

      // Sort results by highest score
      const sortedResults = gradedResults.sort((a, b) => b.score - a.score);
      setResults(sortedResults);

    } catch (error) {
      console.error("Arena Error:", error);
      alert("A fatal error occurred during the Arena run. Check the console.");
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <div className="p-8 md:p-12 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="flex items-center gap-4 border-b border-white/10 pb-6">
        <div className="p-3 bg-indigo-500/10 rounded-2xl ring-1 ring-indigo-500/20">
          <Swords className="w-8 h-8 text-indigo-400" />
        </div>
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white">Multi-Model Arena</h1>
          <p className="text-zinc-400 mt-1">Pit AI models against each other in real-time and let the Universal Judge decide the winner.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column: Command Controls */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-white/[0.02] border border-white/10 rounded-2xl p-6">
            
            <label className="block text-sm font-medium text-zinc-400 mb-3">1. Select Competitors</label>
            <div className="mb-5">
              {MODEL_REGISTRY.map(model => (
                <label key={model.id} className="flex items-center gap-3 p-3 rounded-xl hover:bg-white/[0.02] cursor-pointer ring-1 ring-transparent hover:ring-white/5 transition-all">
                  <div className="relative flex items-center justify-center">
                    <input 
                      type="checkbox"
                      checked={selectedModels.includes(model.id)}
                      onChange={() => handleToggleModel(model.id)}
                      className="peer sr-only"
                    />
                    <div className="w-5 h-5 rounded border border-zinc-600 bg-zinc-900 peer-checked:bg-indigo-500 peer-checked:border-indigo-500 transition-colors flex items-center justify-center">
                      <CheckCircle className="w-3 h-3 text-white opacity-0 peer-checked:opacity-100 scale-50 peer-checked:scale-100 transition-all" />
                    </div>
                  </div>
                  <span className="text-sm font-medium text-zinc-300">{model.label}</span>
                  <span className="ml-auto text-xs text-zinc-600">{model.provider}</span>
                </label>
              ))}
            </div>

            <label className="block text-sm font-medium text-zinc-400 mb-2">2. Enter Challenge Prompt</label>
            <textarea 
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="w-full h-30 bg-[#0c0c0e] border border-white/10 rounded-xl p-4 text-sm text-zinc-300 outline-none focus:ring-2 focus:ring-indigo-500 resize-none mb-2"
              placeholder="Paste a coding problem here to broadcast to all selected models..."
            />

            <button 
              onClick={handleRunArena}
              disabled={isRunning || selectedModels.length < 2 || !prompt.trim()}
              className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-3.5 px-4 rounded-xl flex items-center justify-center gap-2 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-[0_0_20px_rgba(79,70,229,0.15)] hover:shadow-[0_0_30px_rgba(79,70,229,0.3)]"
            >
              {isRunning ? <Loader2 className="animate-spin w-5 h-5" /> : <Play className="w-5 h-5" />}
              {isRunning ? 'Running Arena...' : 'Commence Battle'}
            </button>
          </div>
        </div>

        {/* Right Column: Battle Results */}
        <div className="lg:col-span-8">
          {results.length === 0 ? (
            <div className="h-full min-h-[400px] flex flex-col items-center justify-center text-center p-8 bg-white/[0.01] border border-dashed border-white/10 rounded-2xl">
              <Swords className="w-16 h-16 text-zinc-700 mb-4" />
              <h3 className="text-xl font-medium text-zinc-300 mb-2">Awaiting Combatants</h3>
              <p className="text-zinc-500 max-w-sm">Select at least two models and enter a prompt to begin the automated benchmarking process.</p>
            </div>
          ) : (
            <div className="space-y-4 animate-in slide-in-from-bottom-4 duration-500">
              {results.map((result, index) => (
                <ArenaResultCard 
                  key={result.modelId} 
                  result={result} 
                  isWinner={index === 0 && result.score > 0} 
                />
              ))}
            </div>
          )}
        </div>
        
      </div>
    </div>
  );
}